#################################
#          ______               #
#    _____/ ____/___  ________  #
#   / ___/ /   / __ \/ ___/ _ \ #
#  / /  / /___/ /_/ / /  /  __/ #
# /_/   \____/\____/_/   \___/  #
#                               #
#################################

server-info:
  name: "Staging Server"
  group: "Staging Servers"

chatFormat:
  text: "{tag} {rank} {name}: {message}"
  enabled: true

discord_webhook:
  status: true
  url:
    grants: ""
    punishments: ""
    ranks: ""
    codes: "https://discord.com/api/webhooks/1239286921126219816/RpSQ9Ou7_aXpVpFfYC_ynkSwxTp0LWzMBafrHjEGRXXA6vMX_1vssd-QIIeum9hy1Lnn"
    tags: ""
    servers: "https://discord.com/api/webhooks/1239300857791643728/paNYgZ1k5NxzO4GpHNwq6e94a434GIFpg2xZ99H19oLKaflnl_COwhdYFD5TyR5d7_Ot"
    reports: ""

coinshop_menus:
  - "general"
  - "extra"

tips:
  settings:
    status: true
    interval: 3 # Interval in minutes
    random: false
    sound: "NOTE_PLING"
    volume: 2.5f
    pitch: 0.15f
  messages:
    '1':
      - "Tip: This is a test of 1 tip"
    '2':
      - "Tip: This is a test of 2 tip"
    '3':
      - "Tip: This is a test of 3 tip"